### PR TITLE
Patch Add an extra ListingTemplate condition

### PR DESCRIPTION
**Pull request by guywatson**
I have my own implementation of a ListingPage and do not use the ListingTemplate/ListingPage module.
The extra condition ensures this logic if skipped if the ListingTemplate/ListingPage module is not being used but seperate ListingPage object has been defined.

### CODE REVIEW

**Comment by nyeholt** [comment]
Technically the if conditional should only need to check for the presence of ListingTemplate as that is the object being used (regardless of the context of what module defines it) 

Separately though, it really should be making use of an extension to the NotifyUsersWorkflowAction class and using updateCMSFields for binding in the selection field rather than how it currently works. Any chance you'd be able to do that instead?

**Comment by guywatson** [comment]
@nyeholt Sure I could do this. Would you like the extension applied in the advancedworkflow module .yml or the extension to simply exist in the module so people can optionally enable the extension in their own .yml files.

**Comment by nyeholt** [comment]
Hmm... realistically it should be an optionally enabled extension, however if it's not applied by default it'd be backwards compatible breaking, so I guess it needs to be applied by default.

**Comment by robbieaverill** [comment]
I'm going to close this since it's unfortunately been neglected. Feel free to reopen this and rebase if you'd like it to be revived. Thanks for contributing @guywatson =)

**Pull request closed without merging**
