### PR TITLE
Fix unit test and extension

### PR DESCRIPTION
**Pull request by flamerohr**

### CODE REVIEW

**Comment by tractorcow** [comment]
It needs a rebase; CI doesn't seem to be running on this PR.

**Comment by flamerohr** [comment]
rebased

**Comment by tractorcow** [comment]
Doh, same problem as https://github.com/silverstripe-australia/silverstripe-advancedworkflow/pull/281.

**Comment by flamerohr** [comment]
would you be able to merge https://github.com/silverstripe-australia/silverstripe-advancedworkflow/pull/283 first, to get around these problems? 😛

**Comment by tractorcow** [comment]
ok, I've merged that one.

**Comment by robbieaverill** [comment]
As of the latest commit to master branch, this has been fixed now :) https://github.com/symbiote/silverstripe-advancedworkflow/blob/99ec428e1d8e930ebabd4c17b2acdab7f536da16/code/extensions/WorkflowEmbargoExpiryExtension.php#L541

**Pull request closed without merging**
