### PR TITLE
Fix conflict with silverstripe/sharedraftcontent

### PR DESCRIPTION
**Pull request by SimoTod**
silverstripe/sharedraftcontent relies on the CanEdit permission in order to understand if a user is allowed to generate a sherable link.

the advancedWorkflow package extends the CanEdit hook returning false for pages in the middle of a workflow when user is not an admin.

As a result, when a user with the right permissions tries to generate a link for a page which needs to be approved, they get an error.

This PR fixes the conflict between the 2 libraries.

### CODE REVIEW

**Comment by robbieaverill** [comment]
Thanks for the pull request @SimoTod. I think there's probably a way we can fix this without adding coupling directly into the code. Will schedule some time to look at this.

**Comment by SimoTod** [comment]
Thanks @robbieaverill
I know, ideally the change should be in silverstripe/sharedraftcontent which should use a custom permission rather then $page->canEdit but it would be a breaking change so I don't want to break others people's projects.
However, I'm happy to send another PR to the other repository if you think it's better.
Let me know, thanks. 
Simone

**Comment by robbieaverill** [comment]
I feel like generating a link to view draft content of the page should only require "can view" permission, rather than "can edit". I realise that under the hood it generates a share token and writes it to the record, but perhaps we can do that in the sharedraftcontent module in a way that doesn't check for canEdit() permission. I'm having a look at this now.

**Comment by robbieaverill** [comment]
I've raised https://github.com/silverstripe/silverstripe-sharedraftcontent/issues/94 to track this

**Comment by robbieaverill** [comment]
@SimoTod I've patched sharedraftcontent to fix this bug: https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/95. Would you mind giving it a test and a code review?

**Comment by SimoTod** [comment]
Thanks @robbieaverill, I'll have a look. Just to know, are you going to apply the fix to branch 2.1 as well? I actually need the feature for a ss4.2 site and we don't have a plan to update and retest everything right now.

**Comment by robbieaverill** [comment]
Yeah we can backport it, no problem

**Comment by SimoTod** [comment]
Thanks, much appreciated. The PR looks good.

**Pull request closed without merging**
